# Generated by Django 3.2.8 on 2021-11-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chatGroup',
            new_name='chat_group',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timeStamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplierid',
            new_name='supplier_id',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='legalName',
            new_name='legal_name',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='taxId',
            new_name='tax_id',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='groupName',
            new_name='groupname',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='restaurantid',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='taxId',
            new_name='tax_id',
        ),
    ]
