# Generated by Django 3.2.8 on 2021-11-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20211101_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='restaurant',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='chatgroup',
            old_name='supplier',
            new_name='supplier_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat_group',
            new_name='chatgroup',
        ),
    ]
