# Generated by Django 3.2.8 on 2021-11-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20211101_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='groupname',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
