# Generated by Django 3.2.8 on 2021-11-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_supplier_groupname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatGroup',
        ),
    ]
