# Generated by Django 3.2.8 on 2021-11-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_delete_chatgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='groupname',
        ),
        migrations.AlterField(
            model_name='message',
            name='chatgroup',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
